services:
  - type: web
    name: teketeke
    env: node
    rootDir: .
    plan: free
    buildCommand: npm ci
    startCommand: node server.js
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE
        sync: false
      - key: SUPABASE_JWT_SECRET
        sync: false
      - key: ADMIN_TOKEN
        sync: false

