server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: teketeke-node
    static_configs:
      - targets: [localhost]
        labels:
          job: teketeke
          host: ${HOSTNAME}
          __path__: /var/log/teketeke/*.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            msg: msg
            req: req
            res: res
            request_id: request_id
      - labels:
          level:
      - replace:
          expression: '.*'
          source: 'req.method'
          replace: '${0}'
      - json:
          source: req
          expressions:
            method: method
            url: url
            route: url
      - json:
          source: res
          expressions:
            status: statusCode
      - labels:
          method:
          status:
      - timestamp:
          source: time
          format: RFC3339Nano

