name: OpenAPI Validation

on:
  push:
  pull_request:

jobs:
  lint-openapi:
    name: Lint OpenAPI Spec
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.19.0'
          cache: 'npm'

      - name: Lint OpenAPI Spec
        run: npx -y @redocly/cli@2.5.0 lint openapi.yaml

      - name: Validate with swagger-cli (OpenAPI 3)
        run: npx -y swagger-cli@4 validate openapi.yaml

      - name: Bundle openapi.yaml (sanity)
        run: npx -y @redocly/cli@latest bundle openapi.yaml --output ./openapi.bundle.json
