name: Stack Readiness

on:
  workflow_dispatch:
    inputs:
      base:
        description: "Base URL to probe (deploy or alias)"
        required: true
        default: "https://teketeke-an8u1azlg-teketeke.vercel.app"
      check_domain:
        description: "Also check apex/www + HSTS?"
        type: boolean
        required: true
        default: true
      apex:
        description: "Apex domain (if check_domain)"
        required: false
        default: "teketeke.app"
      www:
        description: "WWW domain (if check_domain)"
        required: false
        default: "www.teketeke.app"
      strict:
        description: "Fail the job if any FAIL lines appear"
        type: boolean
        required: true
        default: false

permissions:
  contents: read

concurrency:
  group: stack-readiness
  cancel-in-progress: true

jobs:
  readiness:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4

      - name: Preflight
        run: |
          set -euo pipefail
          BASE="${{ inputs.base }}"
          if [[ -z "$BASE" ]]; then
            echo "::error::Missing input 'base'"
            exit 1
          fi
          if ! echo "$BASE" | grep -Eq '^https://'; then
            echo "::warning::Base does not look like an https URL: $BASE"
          fi
          echo "Target base: $BASE"

      - name: Install deps
        run: |
          set -euo pipefail
          sudo apt-get update -y
          sudo apt-get install -y jq dnsutils

      - name: Run readiness report
        id: run
        env:
          # Provide both names for script compatibility
          BASE_URL: ${{ inputs.base }}
          BASE: ${{ inputs.base }}
          # Fallback so first run (or forks) doesn't bail on empty secret
          ADMIN_TOKEN: ${{ secrets.TEKETEKE_ADMIN_TOKEN || secrets.ADMIN_TOKEN || 'dummy-admin-token' }}
          # Only pass APEX/WWW when check_domain=true
          APEX: ${{ inputs.check_domain && inputs.apex || '' }}
          WWW: ${{ inputs.check_domain && inputs.www || '' }}
        run: |
          set -euo pipefail
          mkdir -p artifacts
          bash scripts/stack-readiness.sh | tee artifacts/readiness.txt

          {
            echo "### Stack Readiness Report"
            echo
            echo "**Target:** $BASE"
            echo
            sed -n '1,999p' artifacts/readiness.txt
          } >> "$GITHUB_STEP_SUMMARY"

          if grep -qE '^FAIL \|' artifacts/readiness.txt; then
            echo "had_failures=true"  >> "$GITHUB_OUTPUT"
          else
            echo "had_failures=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Upload report artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: readiness-report
          path: |
            artifacts/readiness.txt
            REPORTS/READINESS.md
          retention-days: 7
          if-no-files-found: warn

      - name: Enforce strict mode
        if: ${{ inputs.strict && steps.run.outputs.had_failures == 'true' }}
        run: |
          echo "FAIL lines detected and strict=true — failing the job."
          exit 1
